### ISSUE TITLE
Which licence is this issued under?

### ISSUE THREAD

**Issue by davidgeary** [better-js-logging/angular-logger2#3]
The [README](https://github.com/better-js-logging/angular-logger2/blob/master/README.md) currently shows the licence as MIT (as was what I assume was this project's predecessor [angular-logger](https://github.com/better-js-logging/angular-logger)).  But the [LICENCE](https://github.com/better-js-logging/angular-logger2/blob/master/LICENSE) file is actually for Apache 2.0.

Am I correct in thinking that the README is wrong?

**Comment by bbottema** [comment]
Ahh yes, I'll update it shortly. Thanks for the heads-up.
